apiVersion: v1
kind: Service
metadata:
  name: dev-cluster
  namespace: dev
spec:
  selector:
    app: vcluster
    release: dev
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  type: LoadBalancer
