apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: frontend
  labels:
    app: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/cm
            name: demo-volume
      volumes:
        - name: demo-volume
          configMap:
            name: demo-cm

