apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: frontend
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
