apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: frontend
spec:
  limits:
    - default:
        memory: "100Mi"
      defaultRequest:
        memory: "50Mi"
      type: Container